spring.application.name=insighton-front

server.port=8080

# front\uAC00 \uC5B4\uB514\uC5D0 \uC788\uB358 Eureka\uD55C\uD14C \uB4F1\uB85D\uD558\uAE30 \uC704\uD574 \uCC3E\uB294 \uC8FC\uC18C, \uD558\uB098\uAC00 \uC8FD\uC5B4\uB3C4 \uB2E4\uB978 \uCABD\uC73C\uB85C \uB4F1\uB85D/\uC870\uD68C \uD558\uB2A5\uD558\uAC8C \uD568
eureka.client.service-url.defaultZone=http://insighton-eureka:8761/eureka/

# ip \uAE30\uBC18 \uB4F1\uB85D, container \uD658\uACBD\uC5D0\uC11C\uB294 \uD544\uC694\uD568
eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true

eureka.client.allow-redirects=false
eureka.client.enabled=false

management.endpoints.web.exposure.include=health
