spring.application.name=insighton-front

server.port=8080

management.endpoints.web.exposure.include=health

service-url.gateway=http://insighton-gateway

server.tomcat.use-relative-redirects=true

spring.config.import=classpath:config/prod/redis.properties