spring.application.name=insighton-front

server.port=10440

# front가 어디에 있던 Eureka한테 등록하기 위해 찾는 주소, 하나가 죽어도 다른 쪽으로 등록/조회 하능하게 함
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:testuser}:${EUREKA_PASSWORD:testpassword}@localhost:10444/eureka/,http://${EUREKA_USERNAME:testuser}:${EUREKA_PASSWORD:userpassword}@localhost:10445/eureka/

# ip 기반 등록, container 환경에서는 필요함
eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health
