spring.application.name=insighton-front

server.port=8400

management.endpoints.web.exposure.include=health
service-url.gateway=http://localhost:8500
server.forward-headers-strategy=framework

spring.config.import=classpath:config/dev/redis.properties, classpath:config/dev/zipkin.properties

logging.level.root=INFO
logging.level.com.nhnacademy.insightonfront=DEBUG