name: front CD

on:
  workflow_run:
    workflows: ["front CI"]
    types: [completed]
    branches: [main]
jobs:
  build-and-push:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      full_image: ${{ steps.image.outputs.full_image }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image name transform into lowercase
        id: image
        run: |
          ORG_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "full_image=ghcr.io/${ORG_LOWER}/insighton-front" >> "$GITHUB_OUTPUT"

      - name: Docker Image Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.full_image }}:latest
            ${{ steps.image.outputs.full_image }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Copy deploy script to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/deploy.sh"
          target: "~/deploy/"

      - name: server ssh rolling deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ~/deploy/scripts/deploy.sh
            ~/deploy/scripts/deploy.sh "${{ needs.build-and-push.outputs.full_image }}:latest"