# 이 워크플로우의 이름, GitHub에서 Actions 탭에 이 이름으로 목록에 나타남
name: front CI

# 언제 이 workflow를 실행하지 정의
on:
  push:
    branches: [main, develop] # 브랜치에 commit이 push되면
  pull_request:
    branches: [main] # main으로 향하는 PR이 열리거나 업데이트되면 실행 (merge 전에 미리 검증하려는 목)

# 작업 단위를 정의
jobs:
  build-and-test:
    runs-on: ubuntu-latest # ubuntu 가상머신에서 실행

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: JDK 21 Install
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: | 
            ${{ runner.os }}-maven-

      - name: Build and Test
        run: mvn -B clean verify